services:
  app:
    stdin_open: true
    tty: true
    image: container-ywsm990
    build:
      context: ./src
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./src/web
        target: /usr/src/app
    environment:
      ALLOWED_HOSTS: "127.0.0.1,localhost"
      DEBUG: True
      SECRET_KEY: local_development